# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}
    ports:
      - "8400:8400"
    environment:
      - NODE_ENV=production
    # volumes:
    #   - .:/app
    #   - /app/node_modules