export interface institutionFields {
    inst_id?: number;
    inst_email?: string;
    inst_password?: string;
    inst_name_th?: string;
    inst_name_en?: string;
    inst_abbr_th?: string;
    inst_abbr_en?: string;
    inst_type?: string;
    inst_phone?: string;
    website?: string;
    address?: string;
    subdistrict?: string;
    district?: string;
    province?: string;
    postal_code?: string;
    logo_url?: string;
    docs_url?: string;
    approve_status?: string;
    flag_valid?: boolean;
    created_at?: string;
    updated_at?: string;
    offset?: number;
    limit?: number;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
    total_count?: number;
    from?: string;
    keyword?: string;
}